@extends('layouts.app')
@section('title')
publications
@endsection
@section('content')
<table>
  <thead>
    <th>id</th>
    <th>title</th>
    <th>status</th>
    <th>type</th>
    <th>target</th>
    <th>operations</th>
  </thead>
  <tbody>
    @foreach($publications as $publication)
      <tr>
        <td>{{$publication->id}}</td>
        <td>{{$publication->title}}</td>
        <td>{{$publication->get_status()}}</td>
        <td>{{$publication->get_type()}}</td>
        <td>{{$publication->target}}</td>
        <td>
          <a href="{{route('normal.publications.show', ['publication' => $publication])}}">show</a>
        </td>
      </tr>
    @endforeach
  </tbody>
</table>
@endsection
